language: go
git:
  depth: false
addons:
  apt:
    packages:
    - ruby-dev
    - rpm
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - zip
go:
  - 1.12.x
services:
  - docker
install:
  - mkdir -p $GOPATH/bin
  # Download the `dep` binary to bin folder in $GOPATH
  - curl -sLo $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.5.3/dep-linux-amd64
  - chmod +x $GOPATH/bin/dep
  # download super-linter: golangci-lint
  - curl -sL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - rvm install 2.0.0
  - rvm 2.0.0 do gem install --no-document fpm
before_script:
  - source .metadata.sh
script:
  - make docker
  # Test built docker image.
  - docker run $DHUSER/$BINARY:local -v 2>&1
  - docker run $DHUSER/$BINARY:local -v 2>&1 | grep -Eq "^$BINARY v$VERSION"
  # test and build everything
  - rvm 2.0.0 do make release
after_success:
  # Display Release Folder
  - ls -l release/
  - |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    # Get deploy key for golift/homebrew-mugs.
    openssl aes-256-cbc -K $encrypted_bff04eff92fa_key -iv $encrypted_bff04eff92fa_iv -in ".travis/github_deploy_key.enc" -out "$SSH_FILE" -d
    chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
        "Host github.com" \
        "  IdentityFile $SSH_FILE" \
        "  StrictHostKeyChecking no" \
        "  LogLevel ERROR" >> ~/.ssh/config
deploy:
  - provider: releases
    overwrite: true
    skip_cleanup: true
    file_glob: true
    api_key:
      secure: bYHilykJ4gTeeUij+6aNsbV4nLNZUyaNI64KtjFvB9jzFK8g3PMMPOoAsPjAPV0gkxguYkrSnQGrsk6LWJS6SdwohvHaRh55keyPfSXuBzogtUyFAT4mS1Ac5/ytXxMm/ry7Z9WbQht0nrI9RhKjtlR5LqaoWkAFidPGBYP1ThVvDqfi4azUjC77y5lS05lRZSzHTOxJm0VKeYuXYHzOV+p7q+C7vU/FGtAJctgcuWokniTE4GTrEQYviZ57LETASKhopuMT79jJqefkW2pVUKRct73NcLF8B/SGFpNT/r51XjXRLVP29JZXmimXAiVe320QYTZPQv+VnYW4gqwt26BDhjw+oa2R1PC8DKNOtgAce6Et/T/UPqQtEV3YuCTKOCPbEpMYH0RuQu3hJcNowp6OWxPkPB/yebkw4FWHN+ue3fzbLpmbnbFk+CdD+0/Ii0eypszKIMlZKHhd8XDNC+LnGH1nYA5XcMfaiLCfSfx4NqK368vN/i0oww/b9SSM9vvYz7hcc2dOa8zI1leIRPISYBWsbgKphB+Pm76VnmFAqgPSrdXn4lnxUV4/q8Nc4YHxSTXheaZCe+PX55CFkN4SyjKbCHMttTL3B8GuPndUKfrYXsufLVfkcY9O31btfHKMa87apTqXGx3VNWd/U4VDioVf1DQAlZgXrLF6hMs=
    file: release/*
    on:
      tags: true
  - provider: script
    script: scripts/formula-deploy.sh
    on:
      tags: true
