language: go
git:
  depth: false
# If your repo name is different than the binary name, you may need to set this.
#go_import_path: github.com/golift/application-builder
addons:
  apt:
    packages:
    - ruby-dev
    - rpm
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - zip
go:
  - 1.12.x
services:
  - docker
install:
  - mkdir -p $GOPATH/bin
  # Download the `dep` binary to bin folder in $GOPATH
  - curl -sLo $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.5.3/dep-linux-amd64
  - chmod +x $GOPATH/bin/dep
  # download super-linter: golangci-lint
  - curl -sL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - rvm install 2.0.0
  - rvm 2.0.0 do gem install --no-document fpm
before_script:
  - openssl aes-256-cbc -K $encrypted_bff04eff92fa_key -iv $encrypted_bff04eff92fa_iv -in .secret_files.tar.enc -out .secret_files.tar -d
  - tar -xf .secret_files.tar
  - source .metadata.sh
  - make vendor
script:
  # Test Go and Docker.
  - make test
  - make docker
  # Test built docker image.
  - docker run $DHUSER/$BINARY:local -v 2>&1 | grep -Eq "^$BINARY v$VERSION"
  # build everything
  - rvm 2.0.0 do make release
after_success:
  # Display Release Folder
  - ls -l release/
  - |
    mkdir -p $HOME/.ssh
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    mv github_deploy_key $SSH_FILE
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
    chmod 600 "$SSH_FILE"
    printf "%s\n" \
      "Host github.com" \
      "  IdentityFile $SSH_FILE" \
      "  StrictHostKeyChecking no" \
      "  LogLevel ERROR" >> $HOME/.ssh/config
deploy:
  - provider: releases
    api_key:
      secure: bYHilykJ4gTeeUij+6aNsbV4nLNZUyaNI64KtjFvB9jzFK8g3PMMPOoAsPjAPV0gkxguYkrSnQGrsk6LWJS6SdwohvHaRh55keyPfSXuBzogtUyFAT4mS1Ac5/ytXxMm/ry7Z9WbQht0nrI9RhKjtlR5LqaoWkAFidPGBYP1ThVvDqfi4azUjC77y5lS05lRZSzHTOxJm0VKeYuXYHzOV+p7q+C7vU/FGtAJctgcuWokniTE4GTrEQYviZ57LETASKhopuMT79jJqefkW2pVUKRct73NcLF8B/SGFpNT/r51XjXRLVP29JZXmimXAiVe320QYTZPQv+VnYW4gqwt26BDhjw+oa2R1PC8DKNOtgAce6Et/T/UPqQtEV3YuCTKOCPbEpMYH0RuQu3hJcNowp6OWxPkPB/yebkw4FWHN+ue3fzbLpmbnbFk+CdD+0/Ii0eypszKIMlZKHhd8XDNC+LnGH1nYA5XcMfaiLCfSfx4NqK368vN/i0oww/b9SSM9vvYz7hcc2dOa8zI1leIRPISYBWsbgKphB+Pm76VnmFAqgPSrdXn4lnxUV4/q8Nc4YHxSTXheaZCe+PX55CFkN4SyjKbCHMttTL3B8GuPndUKfrYXsufLVfkcY9O31btfHKMa87apTqXGx3VNWd/U4VDioVf1DQAlZgXrLF6hMs=
    overwrite: true
    skip_cleanup: true
    file_glob: true
    file: release/*
    on:
      tags: true
  - provider: script
    script: scripts/formula-deploy.sh
    on:
      tags: true
